# 双服务器智能分流配置 - 优化工作版
# 基于测试成功的简化配置改进
# 最后更新: 2025-07-31 23:12:39 - 添加google.com全域名到AI-Services

mixed-port: 7890          # HTTP+SOCKS+TUN复用端口
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

# 流量嗅探 - 确保QUIC/UDP被正确识别和代理
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443]
      override-destination: true
    HTTP:
      ports: [80, 443]
      override-destination: false
  force-dns-mapping: true
  parse-pure-ip: true

# TUN模式 - 确保所有UDP/TCP流量进入代理隧道
tun:
  enable: true
  stack: system       # macOS/Linux兼容
  auto-route: true
  dns-hijack:
    - any:53

# DNS配置 - fake-ip模式确保DoH/QUIC被拦截
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip          # 关键：强制映射到假地址
  nameserver:
    - https://1.1.1.1/dns-query   # DoH确保安全
    - https://8.8.8.8/dns-query
  proxy-server-nameserver:
    - https://1.1.1.1/dns-query   # 代理流量也走DoH
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*"
    - +.lan
    - +.local
  ipv6: true                      # 启用IPv6支持

# 规则提供器 - 自动更新确保规则完整性
rule-providers:
  Google:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Google.yaml"
    path: ./providers/Google.yaml
    interval: 86400
  
  GoogleIP:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/GoogleCN.yaml"
    path: ./providers/GoogleIP.yaml
    interval: 86400

  OpenAI:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/OpenAi.yaml"
    path: ./providers/OpenAI.yaml
    interval: 86400

proxies:
  # 美国西雅图服务器 - AI专用
  - name: "US-Seattle-Reality"
    type: vless
    server: 104.247.120.132
    port: 443
    uuid: fbe68161-340d-4721-aff4-b0efc1d03bdb
    flow: xtls-rprx-vision
    tls: true
    network: tcp
    reality-opts:
      public-key: 0bMB_OETOiU-J2lr3aoHdBfOIiJzrDYZH1mmYa3_lhU
      short-id: e22fc234aa2b0560
    client-fingerprint: chrome
    servername: www.apple.com

  - name: "US-Seattle-Hysteria2"
    type: hysteria2
    server: 104.247.120.132
    port: 443
    password: SeattleAI2025_1da9543d07a41781
    obfs: salamander
    obfs-password: homeRouter_2ca57d650199
    sni: www.apple.com
    skip-cert-verify: true
    up: 300
    down: 500

  # 香港CMI服务器 - 流媒体专用
  - name: "HK-CMI-Reality"
    type: vless
    server: 38.22.93.165
    port: 443
    uuid: 5dc648a5-96a6-4ad8-a6e3-d0bb6f00850d
    flow: xtls-rprx-vision
    tls: true
    network: tcp
    reality-opts:
      public-key: FvvA271bTh51H7d69nmyriujFP0agStXM4dXEkK46xc
      short-id: d35b027ab42e9018
    client-fingerprint: chrome
    servername: www.binance.com

  - name: "HK-CMI-Hysteria2"
    type: hysteria2
    server: 38.22.93.165
    port: 8443
    password: HKBinance2025_a946373f443e2c4c
    obfs: salamander
    obfs-password: cmi_90a632b97eac
    sni: www.binance.com
    skip-cert-verify: true
    up: 300
    down: 500

proxy-groups:
  # AI服务专用组 - 自动故障转移
  - name: "AI-Services"
    type: fallback            # 自动切换到健康节点
    url: http://www.gstatic.com/generate_204
    interval: 300
    timeout: 3000
    proxies:
      - "US-Seattle-Hysteria2"  # 优先使用Hysteria2
      - "US-Seattle-Reality"

  # 流媒体专用组
  - name: "Streaming"
    type: select
    proxies:
      - "HK-CMI-Hysteria2"  # 优先使用Hysteria2
      - "HK-CMI-Reality"
      - "US-Seattle-Hysteria2"

  # Binance交易专用
  - name: "Binance-Trading"
    type: select
    proxies:
      - "HK-CMI-Reality"
      - "HK-CMI-Hysteria2"

  # Apple服务
  - name: "Apple-Services"
    type: select
    proxies:
      - "US-Seattle-Reality"
      - "HK-CMI-Reality"
      - "DIRECT"

  # 国外社交媒体
  - name: "Social-Media"
    type: select
    proxies:
      - "Auto-Select"
      - "HK-CMI-Reality"
      - "US-Seattle-Reality"

  # 智能选择组 - 延迟测试
  - name: "Auto-Select"
    type: url-test
    proxies:
      - "HK-CMI-Hysteria2"
      - "US-Seattle-Hysteria2"
      - "HK-CMI-Reality"
      - "US-Seattle-Reality"
    url: "http://www.gstatic.com/generate_204"
    interval: 300             # 增加测试间隔减少负载
    timeout: 5000             # 增加超时时间
    tolerance: 150            # 延迟容差

  # 国外网站
  - name: "Foreign-Sites"
    type: select
    proxies:
      - "Auto-Select"
      - "US-Seattle-Hysteria2"
      - "HK-CMI-Hysteria2"

  # 国内直连
  - name: "China-Direct"
    type: select
    proxies:
      - "DIRECT"

rules:
  # AI服务规则 - 优先使用规则提供器 (自动更新，覆盖完整)
  - RULE-SET,Google,AI-Services
  - RULE-SET,OpenAI,AI-Services
  
  # 手动补充AI服务 (规则提供器未覆盖的)
  # Anthropic Claude
  - DOMAIN-SUFFIX,anthropic.com,AI-Services
  - DOMAIN-SUFFIX,api.anthropic.com,AI-Services
  - DOMAIN-SUFFIX,sandbox.api.anthropic.com,AI-Services
  - DOMAIN-SUFFIX,claude.ai,AI-Services
  
  # 手动补充关键Google AI域名 (规则提供器可能未覆盖)
  - DOMAIN,gemini.google.com,AI-Services              # Gemini主站
  - DOMAIN,aistudio.google.com,AI-Services            # Google AI Studio
  - DOMAIN,generativelanguage.googleapis.com,AI-Services  # Gemini API端点
  - DOMAIN-KEYWORD,gemini,AI-Services                 # 兜底匹配
  
  # Cursor IDE (添加更多子域名)
  - DOMAIN-SUFFIX,cursor.com,AI-Services
  - DOMAIN-SUFFIX,api.cursor.com,AI-Services
  - DOMAIN-SUFFIX,download.cursor.com,AI-Services
  - DOMAIN-SUFFIX,auth.cursor.com,AI-Services
  - DOMAIN-SUFFIX,app.cursor.com,AI-Services
  - DOMAIN-KEYWORD,cursor,AI-Services
  
  # Perplexity AI搜索 (底层调用GPT，需要美国IP)
  - DOMAIN-SUFFIX,perplexity.ai,AI-Services
  - DOMAIN-SUFFIX,api.perplexity.ai,AI-Services
  
  # Windsurf AI编程
  - DOMAIN-SUFFIX,windsurf.com,AI-Services
  - DOMAIN-SUFFIX,windsurf.ai,AI-Services

  # 流媒体 - 走香港
  - DOMAIN-SUFFIX,netflix.com,Streaming
  - DOMAIN-SUFFIX,youtube.com,Streaming
  - DOMAIN-SUFFIX,googlevideo.com,Streaming
  - DOMAIN-SUFFIX,ytimg.com,Streaming
  - DOMAIN-SUFFIX,disney.com,Streaming
  - DOMAIN-SUFFIX,hulu.com,Streaming
  - DOMAIN-SUFFIX,telegram.org,Streaming
  - DOMAIN-SUFFIX,t.me,Streaming
  - DOMAIN-KEYWORD,telegram,Streaming

  # Binance交易 - 走香港
  - DOMAIN-SUFFIX,binance.com,Binance-Trading
  - DOMAIN-SUFFIX,bnbstatic.com,Binance-Trading
  - DOMAIN-KEYWORD,binance,Binance-Trading

  # Apple服务
  - DOMAIN-SUFFIX,apple.com,Apple-Services
  - DOMAIN-SUFFIX,icloud.com,Apple-Services
  - DOMAIN-SUFFIX,appstore.com,Apple-Services

  # 国外社交媒体
  - DOMAIN-SUFFIX,twitter.com,Social-Media
  - DOMAIN-SUFFIX,x.com,Social-Media
  - DOMAIN-SUFFIX,instagram.com,Social-Media
  - DOMAIN-SUFFIX,facebook.com,Social-Media
  - DOMAIN-SUFFIX,linkedin.com,Social-Media
  - DOMAIN-SUFFIX,reddit.com,Social-Media

  # 国内社交媒体和通讯 - 直连
  - DOMAIN-SUFFIX,qq.com,China-Direct
  - DOMAIN-SUFFIX,weixin.qq.com,China-Direct
  - DOMAIN-KEYWORD,wechat,China-Direct
  - DOMAIN-SUFFIX,xiaohongshu.com,China-Direct
  - DOMAIN-SUFFIX,xhscdn.com,China-Direct
  - DOMAIN-SUFFIX,bilibili.com,China-Direct
  - DOMAIN-SUFFIX,bilivideo.com,China-Direct
  - DOMAIN-SUFFIX,douyin.com,China-Direct
  - DOMAIN-SUFFIX,douyinpic.com,China-Direct
  - DOMAIN-SUFFIX,douyincdn.com,China-Direct
  - DOMAIN-KEYWORD,douyin,China-Direct

  # 国内网站 - 直连
  - DOMAIN-SUFFIX,cn,China-Direct
  - DOMAIN-SUFFIX,baidu.com,China-Direct
  - DOMAIN-SUFFIX,taobao.com,China-Direct
  - DOMAIN-SUFFIX,jd.com,China-Direct
  - DOMAIN-SUFFIX,alipay.com,China-Direct
  - DOMAIN-KEYWORD,-cn,China-Direct

  # 其他Google服务 (非AI) - 走代理
  - DOMAIN-SUFFIX,gmail.com,Foreign-Sites
  - DOMAIN-SUFFIX,googledrive.com,Foreign-Sites

  # 本地网络
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT

  # 默认规则
  - GEOIP,CN,China-Direct
  - MATCH,Foreign-Sites

